//
// $Id$

#include <iostream>

#include <QFile>
#include <QString>
#include <QTextStream>

using namespace std;

/**
 * Meta Type Compiler.
 */
int main (int argc, char** argv)
{
    // process the command line arguments
    QString input;
    QString output;
    for (int ii = 1; ii < argc; ii++) {
        QString arg(argv[ii]);
        if (!arg.startsWith('-')) {
            input = arg;
            continue;
        }
        QStringRef name = arg.midRef(1);
        if (name == "o") {
            if (++ii == argc) {
                cerr << "Missing file name argument for -o" << endl;
                return 1;
            }
            output = argv[ii];

        } else {
            cerr << "Unknown option " << arg.toStdString() << endl;
            return 1;
        }
    }
    if (input.isNull()) {
        cerr << "Usage: mtc [OPTION]... input file" << endl;
        cerr << "Where options include:" << endl;
        cerr << "  -o filename: Send output to filename rather than standard output." << endl;
        return 0;
    }

    // attempt to open the input and output files
    QFile ifile(input);
    if (!ifile.open(QIODevice::ReadOnly | QIODevice::Text)) {
        cerr << ("Couldn't open " + input + ": " + ifile.errorString()).toStdString() << endl;
        return 1;
    }
    QFile ofile(output);
    if (output.isNull()) {
        ofile.open(stdout, QIODevice::WriteOnly | QIODevice::Text);

    } else if (!ofile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        cerr << ("Couldn't open " + output + ": " + ofile.errorString()).toStdString() << endl;
        return 1;
    }

    QTextStream istream(&ifile);

    QTextStream ostream(&ofile);
    ostream << "// generated by mtc\n";
    ostream << "#include \"" << input << "\"\n";

    return 0;
}
